### ISSUE TITLE
How to use the .dll

### ISSUE THREAD

**Issue by caoyongfeng0214** [nietras/Llm.cs#16]
@nietras 
Thank you for developing this project.
Please provide some documentation and code samples.

- How to create myself model (base on other model).
- How to append some new text to myself model.
- How to start train myself model.
- How to input some text and output sequence completion.

Thanks.

**Comment by nietras** [comment]
@caoyongfeng0214 this project is not intended for actual real world usage, it's a toy project for fun and education based in llm.c. Hence, there are no plans for docs or samples or similar.
